export default [
  {
    id: 1,
    imdbId: 'tt15059490',
    title: 'Embedded',
    originalTitle: 'Encajada',
    overview:
      'Alodia is in the middle of a diode laser session. It is interrupted because of an error that forces her to get up. The escapism no longer works for her and redemption is the only thing left.',
    runtime: 14,
    releaseDate: '2022-11-03',
    genres: ['Drama', 'Science Fiction', 'Thriller'],
    country: ['Spain'],
    language: 'Spanish',
    movieStatus: 'Released',
    popularity: 0.103,
    budget: 0,
    revenue: 0,
    ratingAverage: 2,
    ratingCount: 1,
    posterUrl: 'https://image.tmdb.org/t/p/w500/9fRCTVHIlD2SXSs2TRsB7ATd3HV.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 2,
    imdbId: 'tt0113101',
    title: 'Four Rooms',
    originalTitle: 'Four Rooms',
    overview:
      "It's Ted the Bellhop's first night on the job...and the hotel's very unusual guests are about to place him in some outrageous predicaments. It seems that this evening's room service is serving up one unbelievable happening after another.",
    runtime: 98,
    releaseDate: '1995-12-09',
    genres: ['Comedy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 8.144,
    budget: 4000000,
    revenue: 4257354,
    ratingAverage: 5.9,
    ratingCount: 2670,
    posterUrl: 'https://image.tmdb.org/t/p/w500/pyCk5JgtRZwRxnXwfrvyzukaKue.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 3,
    imdbId: 'tt0107286',
    title: 'Judgment Night',
    originalTitle: 'Judgment Night',
    overview:
      'Four young friends, while taking a shortcut en route to a local boxing match, witness a brutal murder which leaves them running for their lives.',
    runtime: 109,
    releaseDate: '1993-10-15',
    genres: ['Action', 'Crime', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 6.632,
    budget: 21000000,
    revenue: 12136938,
    ratingAverage: 6.47,
    ratingCount: 345,
    posterUrl: 'https://image.tmdb.org/t/p/w500/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 4,
    imdbId: 'tt16481662',
    title: 'Haunted: Indiana State Sanatorium',
    originalTitle: 'Haunted: Indiana State Sanatorium',
    overview:
      'Three paranormal investigators enter what is said to be the most haunted location in the Midwest. Over the last 100 years, the property has housed thousands of deaths, murder, suicide, and countless acts of foul play.',
    runtime: 85,
    releaseDate: '2022-01-31',
    genres: ['Documentary', 'Horror'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.23,
    budget: 27000,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/dWflHOw0XR9bqo6UfiFSXAPf2fK.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 5,
    imdbId: 'tt0072517',
    title: "It's a Lovely Day Tomorrow",
    originalTitle: "It's a Lovely Day Tomorrow",
    overview:
      "A recreation of a World War II incident which occurred in London's Bethnal Green underground station in 1943, in which 173 people died when a panicked crowd stampeded as they were hurrying down the steps to take refuge from an air raid.",
    runtime: 70,
    releaseDate: '1975-10-08',
    genres: ['Drama', 'TV Movie', 'War'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.211,
    budget: 0,
    revenue: 0,
    ratingAverage: 8,
    ratingCount: 2,
    posterUrl: 'https://image.tmdb.org/t/p/w500/t8nmMGy6xKcfSn7loUUzOJpfeKO.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 6,
    imdbId: 'tt23635146',
    title: '1966: Who Stole The World Cup?',
    originalTitle: '1966: Who Stole The World Cup?',
    overview:
      "From South London spivs to the upper reaches of the 1960s society, this extraordinary true story reveals who stole the World Cup trophy in the lead-up to England's triumph in 1966.",
    runtime: 60,
    releaseDate: '2022-11-14',
    genres: ['Documentary'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.143,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/Al5IvFeMiFjADoxy2DNZNLKRxXv.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 7,
    imdbId: 'tt0076759',
    title: 'Star Wars',
    originalTitle: 'Star Wars',
    overview:
      'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
    runtime: 121,
    releaseDate: '1977-05-25',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 51.968,
    budget: 11000000,
    revenue: 775398007,
    ratingAverage: 8.202,
    ratingCount: 20890,
    posterUrl: 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 8,
    imdbId: 'tt0266543',
    title: 'Finding Nemo',
    originalTitle: 'Finding Nemo',
    overview:
      "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
    runtime: 100,
    releaseDate: '2003-05-30',
    genres: ['Animation', 'Family'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 55.726,
    budget: 94000000,
    revenue: 940335536,
    ratingAverage: 7.817,
    ratingCount: 19469,
    posterUrl: 'https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 9,
    imdbId: 'tt0109830',
    title: 'Forrest Gump',
    originalTitle: 'Forrest Gump',
    overview:
      'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
    runtime: 142,
    releaseDate: '1994-06-23',
    genres: ['Comedy', 'Drama', 'Romance'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 58.313,
    budget: 55000000,
    revenue: 677387716,
    ratingAverage: 8.469,
    ratingCount: 27856,
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 10,
    imdbId: 'tt0169547',
    title: 'American Beauty',
    originalTitle: 'American Beauty',
    overview:
      "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.",
    runtime: 122,
    releaseDate: '1999-09-15',
    genres: ['Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 20.19,
    budget: 15000000,
    revenue: 356296601,
    ratingAverage: 8.009,
    ratingCount: 12183,
    posterUrl: 'https://image.tmdb.org/t/p/w500/6MNwC101wSEsDyxTJBGXsgIMlmh.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 11,
    imdbId: null,
    title: 'Easter Island Underworld',
    originalTitle: 'Easter Island Underworld',
    overview:
      "Deep beneath the legendary Easter Island, National Geographic undertakes a groundbreaking expedition to map a vast cave system utilized by the people who carved these iconic statues. Protected by sheer cliffs, narrow labyrinths and underwater entrances, many of the caves have not been explored for decades. Recently discovered human remains and telltale artifacts reveal details of the island's intriguing history and culture.",
    runtime: 45,
    releaseDate: '2009-05-09',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.002,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/eAPTP8ZhdRCsjWvBF2F6nzozlyi.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 12,
    imdbId: 'tt0411267',
    title: 'The Dark',
    originalTitle: 'The Dark',
    overview:
      'In an attempt to pull her family together, Adèlle travels with her young daughter Sarah to Wales to visit her father. The morning after they arrive, Sarah mysteriously vanishes in the ocean. Not long after, a little girl bearing a striking resemblance to their missing daughter reveals that she has retuned from the dead  — and that Sarah has been taken to the Welsh underworld.',
    runtime: 87,
    releaseDate: '2005-09-28',
    genres: ['Horror', 'Mystery', 'Thriller'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 4.602,
    budget: 0,
    revenue: 6593579,
    ratingAverage: 5.7,
    ratingCount: 277,
    posterUrl: 'https://image.tmdb.org/t/p/w500/h6gCVAzjFLhzkffv2VZO1RgVCBt.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 13,
    imdbId: 'tt0805518',
    title: 'Dunny',
    originalTitle: 'Dunny',
    overview:
      'An obese 11-year-old attempts to give a love letter to his elementary school crush and winds up at dinner with her intensely suburban family and her new flame.',
    runtime: 11,
    releaseDate: '2006-02-01',
    genres: ['Comedy', 'Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.056,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/epnNyBG8d6JkgAWRYrwYMABJQRL.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 14,
    imdbId: null,
    title: 'Dorothée Show',
    originalTitle: 'Dorothée Show',
    overview: 'The romanticized life of Dorothée summarized in various sketches and songs.',
    runtime: 90,
    releaseDate: '1987-12-26',
    genres: ['Comedy', 'Family', 'Music'],
    country: ['France'],
    language: 'French',
    movieStatus: 'Released',
    popularity: 0.187,
    budget: 0,
    revenue: 0,
    ratingAverage: 8,
    ratingCount: 1,
    posterUrl: 'https://image.tmdb.org/t/p/w500/uMSJTJLHge0vBJ2ZlCmK0ZENYKP.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 15,
    imdbId: 'tt0119116',
    title: 'The Fifth Element',
    originalTitle: 'Le Cinquième Élément',
    overview:
      'In 2257, a taxi driver is unintentionally given the task of saving a young girl who is part of the key that will ensure the survival of humanity.',
    runtime: 126,
    releaseDate: '1997-05-02',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    country: ['France'],
    language: 'French',
    movieStatus: 'Released',
    popularity: 27.941,
    budget: 90000000,
    revenue: 263920180,
    ratingAverage: 7.554,
    ratingCount: 10869,
    posterUrl: 'https://image.tmdb.org/t/p/w500/fPtlCO1yQtnoLHOwKtWz7db6RGU.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 16,
    imdbId: 'tt0168629',
    title: 'Dancer in the Dark',
    originalTitle: 'Dancer in the Dark',
    overview:
      "Selma, a Czech immigrant on the verge of blindness, struggles to make ends meet for herself and her son, who has inherited the same genetic disorder and will suffer the same fate without an expensive operation. When life gets too difficult, Selma learns to cope through her love of musicals, escaping life's troubles – even if just for a moment – by dreaming up little numbers to the rhythmic beats of her surroundings.",
    runtime: 140,
    releaseDate: '2000-09-01',
    genres: ['Crime', 'Drama'],
    country: ['Denmark'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 7.884,
    budget: 12500000,
    revenue: 40061153,
    ratingAverage: 7.9,
    ratingCount: 1813,
    posterUrl: 'https://image.tmdb.org/t/p/w500/9rsivF4sWfmBzrNr4LPu6TNJhXX.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 17,
    imdbId: 'tt0325980',
    title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    originalTitle: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    overview:
      "After Port Royal is attacked and pillaged by a mysterious pirate crew, capturing the governor's daughter Elizabeth Swann in the process, William Turner asks free-willing pirate Jack Sparrow to help him locate the crew's ship—The Black Pearl—so that he can rescue the woman he loves.",
    runtime: 143,
    releaseDate: '2003-07-09',
    genres: ['Action', 'Adventure', 'Fantasy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 67.571,
    budget: 140000000,
    revenue: 655011224,
    ratingAverage: 7.807,
    ratingCount: 20900,
    posterUrl: 'https://image.tmdb.org/t/p/w500/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 18,
    imdbId: 'tt24517128',
    title: 'Karagiozis: The Movie',
    originalTitle: 'Καραγκιόζης - The Movie!',
    overview:
      'The village Governor decides to appoint a public secretary to serve the citizens, as his employees are forced to neglect their work to serve their illiterate fellow citizens in their written communication. Hatziavatis undertakes to find the right person for the position, until he meets Karagiozis who impresses him with the grammatical knowledge he says he has and the search ends! After a hilarious meeting with the Governor, Karagiozis becomes the Grammar of the village and, full of appetite and empty of knowledge, grabs a pencil and paper.',
    runtime: 74,
    releaseDate: '2022-12-08',
    genres: ['Animation'],
    country: ['Greece'],
    language: 'Greek',
    movieStatus: 'Released',
    popularity: 0.029,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/hcLPeGdMEQfDtE1WvmZtuKrX9cj.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 19,
    imdbId: 'tt0266697',
    title: 'Kill Bill: Vol. 1',
    originalTitle: 'Kill Bill: Vol. 1',
    overview:
      'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.',
    runtime: 111,
    releaseDate: '2003-10-10',
    genres: ['Action', 'Crime'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 32.975,
    budget: 30000000,
    revenue: 180906076,
    ratingAverage: 8,
    ratingCount: 17630,
    posterUrl: 'https://image.tmdb.org/t/p/w500/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 20,
    imdbId: 'tt0418763',
    title: 'Jarhead',
    originalTitle: 'Jarhead',
    overview:
      "Jarhead is a film about a US Marine Anthony Swofford's experience in the Gulf War. After putting up with an arduous boot camp, Swofford and his unit are sent to the Persian Gulf where they are eager to fight, but are forced to stay back from the action. Swofford struggles with the possibility of his girlfriend cheating on him, and as his mental state deteriorates, his desire to kill increases.",
    runtime: 123,
    releaseDate: '2005-11-04',
    genres: ['Drama', 'War'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 13.633,
    budget: 72000000,
    revenue: 97076152,
    ratingAverage: 6.67,
    ratingCount: 2920,
    posterUrl: 'https://image.tmdb.org/t/p/w500/4rCzaZy5Qkvxh5xaVpHriXSLTgC.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
];
