export default [
  {
    id: 1,
    tmdbId: 1329050,
    imdbId: 'tt11940730',
    title: 'Knock',
    originalTitle: 'Knock',
    overview:
      'Late at night, Kim hears a sound in her apartment. She asks her partner to investigate.',
    runtime: 9,
    releaseDate: '2020-01-01',
    genres: ['Drama', 'Horror', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.011,
    budget: 5000,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/3sTOMFUND84vCBA5RUAzNpPPMZi.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 2,
    tmdbId: 1329454,
    imdbId: 'tt24634278',
    title: 'The Bowery Boys: Legends of Laughter',
    originalTitle: 'The Bowery Boys: Legends of Laughter',
    overview:
      'Thirty years of film clips, interviews, outtakes, stills and more pay tribute to the lives and work of the comedy legends known as the Bowery Boys.',
    runtime: 83,
    releaseDate: '2020-01-01',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.307,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/gAYb3nt4DMsbe69lAdqm5CzYhRy.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 3,
    tmdbId: 1098029,
    imdbId: null,
    title: 'The Travesty of Richard III',
    originalTitle: 'The Travesty of Richard III',
    overview:
      "Shakespeare's Richard Gloucester plots to seize England's Crown! In a world gripped by Covid a dark, thrilling yet jolly comedy leaped from stage to screen. Two actors divided by lockdown; 13 characters brought together by greed, grief and green screens.",
    runtime: 60,
    releaseDate: '2020-01-01',
    genres: ['Comedy'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.012,
    budget: 600,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/9uKAR8zvVZYHHdbJA5PpQZoOj2c.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 4,
    tmdbId: 1098129,
    imdbId: null,
    title: 'The World Before Midnight',
    originalTitle: 'The World Before Midnight',
    overview:
      'Aleksey spends his day trying to figure out his past. But there is one circumstance. This is the last day of the world.',
    runtime: 61,
    releaseDate: '2020-01-01',
    genres: ['Drama'],
    country: ['Russia'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.107,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/n4KnGVPwpr3CbdMsd3I6k1x9ldj.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 5,
    tmdbId: 1336128,
    imdbId: null,
    title: 'The Vision Machine',
    originalTitle: 'The Vision Machine',
    overview:
      'The Vision Machine was filmed at the factory of SIGMA Corporation, a renowned global brand of lenses for photography and cinema production. Like most such manufacturers, it is based in Japan. Using lenses manufactured by the factory, Young filmed their female employees as they performed their usual tasks on the production, assembly and testing process. No men are featured, and while the piece alludes to the genres of documentary or corporate video, it was filmed and edited to suggest a speculative fiction: a lensmaking factory run (and perhaps owned) by women.',
    runtime: 14,
    releaseDate: '2020-01-01',
    genres: ['Documentary', 'Science Fiction'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.015,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/h0BgNKjgmyzr4XKTUdu0Ka5xLed.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 6,
    tmdbId: 1337071,
    imdbId: 'tt33163918',
    title: "Batman '66 Meets the Green Hornet",
    originalTitle: "Batman '66 Meets the Green Hornet",
    overview: `The episodes A Piece of the Action and Batman''s Satisfaction have been edited together, along with other scenes and period TV promos of the 1966 television show Batman and 1967''s The Green Hornet for this interesting feature film.`,
    runtime: 62,
    releaseDate: '2020-01-01',
    genres: ['Action', 'Comedy', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.972,
    budget: 250000,
    revenue: 0,
    ratingAverage: 8,
    ratingCount: 1,
    posterUrl: 'https://image.tmdb.org/t/p/w500/egASVbOqdatbVtekCbTZHKefdOg.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 7,
    tmdbId: 321652,
    imdbId: 'tt3748390',
    title: 'Outpost',
    originalTitle: 'Outpost',
    overview:
      "When the final Citizen of Earth's interplanetary research and diplomacy program finally makes first contact, he's forced to not only protect humanity, but that which makes him human: love.",
    runtime: 17,
    releaseDate: '2020-02-06',
    genres: ['Action', 'Romance', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.155,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.2,
    ratingCount: 4,
    posterUrl: 'https://image.tmdb.org/t/p/w500/siEbbDEM48Aq9Z53sBUz0IIRf4E.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 8,
    tmdbId: 1379471,
    imdbId: null,
    title: 'Balls Out',
    originalTitle: 'Balls Out',
    overview:
      "After hitting a baseball through a window, Silas Bridgewell is framed for murder of his neighbor. So it's up to Detective Solomon Gaines to prove his innocence.",
    runtime: 14,
    releaseDate: '2020-02-21',
    genres: ['Comedy', 'Crime', 'Mystery'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.012,
    budget: 100,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/xNTeoqTfnElB0K00HyL4cTDSfnL.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 9,
    tmdbId: 1379544,
    imdbId: null,
    title: 'Napoleonic Wars: Battle for Germany 1813',
    originalTitle: 'Napoleonic Wars: Battle for Germany 1813',
    overview:
      'In 1813, following his disastrous invasion of Russia, Napoleon faced a desperate battle to save his empire. His enemies were gaining in strength, as Prussia and Sweden joined the Sixth Coalition against him, while Russian armies advanced across Poland and into Germany. The French Emperor worked miracles to raise a new Grande Armée of young conscripts, leading them to victory at Lützen and Bautzen. But Napoleon knew everything might ultimately depend on Austria - which side would his father-in-law, Austrian Emperor Francis I, chose to support? The matter would settled after a fateful and ill-tempered meeting in Dresden between Napoleon and Austrian foreign minister von Metternich...',
    runtime: 25,
    releaseDate: '2020-02-14',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.069,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/wJwymF6UniM2Ma23cbkCk0qc9Dg.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 10,
    tmdbId: 342470,
    imdbId: 'tt3907584',
    title: 'All the Bright Places',
    originalTitle: 'All the Bright Places',
    overview:
      'Two teens facing personal struggles form a powerful bond as they embark on a cathartic journey chronicling the wonders of Indiana.',
    runtime: 108,
    releaseDate: '2020-02-28',
    genres: ['Drama', 'Romance'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 21.296,
    budget: 0,
    revenue: 0,
    ratingAverage: 7.646,
    ratingCount: 2891,
    posterUrl: 'https://image.tmdb.org/t/p/w500/4SafxuMKQiw4reBiWKVZJpJn80I.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 11,
    tmdbId: 1395154,
    imdbId: 'tt13529684',
    title: 'Opium Wars 97',
    originalTitle: 'Opium Wars 97',
    overview:
      'The Opium Wars, a 19th-century armed conflict between the Qing Dynasty and the British Empire, is narrated by a history professor who has a hypnotic effect on his students.',
    runtime: 17,
    releaseDate: '2020-02-15',
    genres: ['History'],
    country: ['Armenia', 'Greece'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.001,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/eaPGhhvht9hM7JWddsdOF0K0pLC.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 12,
    tmdbId: 1396959,
    imdbId: null,
    title: 'Sea Lovers',
    originalTitle: 'Sea Lovers',
    overview:
      "For most of our history, the ocean has been regarded as, if not a barrier, an adversary: something to be simultaneously exploited and feared. Ingo Niermann asks us to rethink our response to the fearful oceans, in hope of finding its hidden soul and reaching an understanding with it. In Sea Lovers Niermann offers us a whole chest of new models for reading, touching and feeling the sea. As the seaside theme parks of the early 20th century offered us a safe encounter with the novel and unsettling technologies of the age, could an underwater amusement park allow us closer interpersonal connection with other lifeforms? And just as the domestication of animals into emotional and affective companions made the forests ‘safe' for our comprehension, could dolphins or cephalopods become our guides to the watery depths that were once our home? Could the salty touch of the ocean itself soften us towards accepting its wild and all-encompassing embrace?",
    runtime: 19,
    releaseDate: '2020-02-20',
    genres: ['Documentary', 'Science Fiction'],
    country: ['Germany', 'Solomon Islands', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.012,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/3eA9Uej0cn6zmGxq4qCbgimfhcp.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 13,
    tmdbId: 1080840,
    imdbId: null,
    title: 'Cirque du Soleil: R.U.N',
    originalTitle: 'Cirque du Soleil: R.U.N',
    overview:
      "Are you ready for another dose of dreamlike impressionism and whimsical flights of fancy? Then you're in the wrong joint.",
    runtime: 107,
    releaseDate: '2020-03-20',
    genres: ['Action', 'Adventure', 'Crime', 'Music'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.092,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/vw3BbFgV6QEIdO9H74re3WrUNXQ.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 14,
    tmdbId: 1412873,
    imdbId: 'tt23752146',
    title: 'A Date with Anxiety',
    originalTitle: 'A Date with Anxiety',
    overview:
      'A college freshman battles the humanized versions of his anxiety while trying to ask out a new crush.',
    runtime: 9,
    releaseDate: '2020-03-20',
    genres: ['Comedy', 'Romance'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.012,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/250W9bqTUCyscKCQYgNIT6c5psW.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 15,
    tmdbId: 705134,
    imdbId: 'tt9562296',
    title: 'Asking for It',
    originalTitle: 'Asking for It',
    overview:
      'A journalist takes justice into her own hands when her internet stalker walks free from the law.',
    runtime: 84,
    releaseDate: '2020-03-07',
    genres: ['Crime'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.644,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.6,
    ratingCount: 5,
    posterUrl: 'https://image.tmdb.org/t/p/w500/qcvEuSJzHuSqH48iZqj7GscPpQE.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 16,
    tmdbId: 1414930,
    imdbId: null,
    title: 'The Gombe Chimpanzee War',
    originalTitle: 'The Gombe Chimpanzee War',
    overview:
      'A hard-hitting first person recount of the Gombe Chimpanzee War, told from the perspective of a melancholic veteran.',
    runtime: 2,
    releaseDate: '2020-03-16',
    genres: ['War'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.012,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/roVtklOJTGzKApDxhDPUCuPv4rY.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 17,
    tmdbId: 367777,
    imdbId: 'tt0259075',
    title: 'An Unkindness of Ravens',
    originalTitle: 'An Unkindness of Ravens',
    overview:
      'When an American writer translates a mysterious Japanese novel his ideas of truth and fiction blur and he begins to question his very existence.',
    runtime: 15,
    releaseDate: '2020-03-13',
    genres: ['Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.183,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/2EacLejfiXwd3S8nv2KddKeUrBW.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 18,
    tmdbId: 1419192,
    imdbId: 'tt12549976',
    title: 'Meet Aaron and His MFA Degree in Acting',
    originalTitle: 'Meet Aaron and His MFA Degree in Acting',
    overview:
      "Meet Aaron. He has his MFA degree in acting. He is in debt for $114,000. And he's never been paid to act. Yet!",
    runtime: 6,
    releaseDate: '2020-04-29',
    genres: ['Comedy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.204,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/ugBlmP12eIryc7LC8gBnpKRGQ2I.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 19,
    tmdbId: 1419270,
    imdbId: 'tt35257688',
    title: 'Perspective',
    originalTitle: 'Perspective',
    overview:
      'A man wakes up. He sees himself and his son playing with time. After a psychedelic journey of absurdity, he finally reaches a level of realization when he understands he has been dreaming in life but continues to dream because that is the truth. Anyhow, that is all about perspectives.',
    runtime: 3,
    releaseDate: '2020-04-14',
    genres: ['Drama', 'Fantasy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.012,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/7G333MrfkPdrHdWJoLC08CC1Ry3.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 20,
    tmdbId: 1421357,
    imdbId: null,
    title: 'The Making of Pyre',
    originalTitle: 'The Making of Pyre',
    overview:
      "Explore the design of perhaps Supergiant Games' most unique game. The vibrant, sporty, mystical world of Pyre.",
    runtime: 30,
    releaseDate: '2020-04-07',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.013,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500None',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 21,
    tmdbId: 1424418,
    imdbId: 'tt6774382',
    title: "Shelby's Haus",
    originalTitle: "Shelby's Haus",
    overview:
      'Shelby takes on the universe, the world and New York City all from the comfort of her haus.',
    runtime: 22,
    releaseDate: '2020-04-12',
    genres: ['Comedy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.057,
    budget: 1000,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/8k8MD16KQ3lMwzIypfQpevxfA13.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 22,
    tmdbId: 1424645,
    imdbId: 'tt11841064',
    title: 'The Trip',
    originalTitle: 'The Trip',
    overview: 'Short film from Nina Guzman',
    runtime: 21,
    releaseDate: '2020-04-20',
    genres: ['Comedy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.013,
    budget: 47750,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500None',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 23,
    tmdbId: 1118008,
    imdbId: 'tt12138288',
    title: 'The 46th Annual Easton High Spelling Bee',
    originalTitle: 'The 46th Annual Easton High Spelling Bee',
    overview:
      'Frank Bickle is roped into the underground crime ring at Easton High School, where he must decide whether or not to throw the Annual Spelling Bee.',
    runtime: 11,
    releaseDate: '2020-04-22',
    genres: ['Comedy', 'Crime'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.015,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/870SNrEkHcZVXFoYYLtt8DF9RBK.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 24,
    tmdbId: 1090178,
    imdbId: 'tt19073170',
    title: 'Money Is The One True God',
    originalTitle: 'Money Is The One True God',
    overview:
      'A kaleidoscope of currency reveals what humans have valued over time. Hi-resolution scans of banknotes from 23 countries ranging from the 1800s to the modern-day. Machine learning programs were used to zoom in on the intricacies of the engravings.',
    runtime: 7,
    releaseDate: '2020-05-08',
    genres: ['Music'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.346,
    budget: 0,
    revenue: 0,
    ratingAverage: 8,
    ratingCount: 1,
    posterUrl: 'https://image.tmdb.org/t/p/w500/fpKiEodEXtaCpQvIjp19lEVFtec.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 25,
    tmdbId: 1090301,
    imdbId: 'tt26217158',
    title: 'The Gig Economy',
    originalTitle: 'The Gig Economy',
    overview:
      'A deep dive into the gig economy reveals its promise and pitfalls through intimate portraits of workers and interviews with leading experts.',
    runtime: 67,
    releaseDate: '2020-05-31',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.041,
    budget: 100000,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/atk9otb7w4HoRvYwrysVgpJPWrA.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 26,
    tmdbId: 475430,
    imdbId: 'tt3089630',
    title: 'Artemis Fowl',
    originalTitle: 'Artemis Fowl',
    overview:
      "Artemis Fowl is a 12-year-old genius and descendant of a long line of criminal masterminds. He soon finds himself in an epic battle against a race of powerful underground fairies who may be behind his father's disappearance.",
    runtime: 94,
    releaseDate: '2020-05-29',
    genres: ['Action', 'Adventure', 'Family', 'Fantasy', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 10.372,
    budget: 125000000,
    revenue: 0,
    ratingAverage: 5.6,
    ratingCount: 1658,
    posterUrl: 'https://image.tmdb.org/t/p/w500/tI8ocADh22GtQFV28vGHaBZVb0U.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 27,
    tmdbId: 482273,
    imdbId: 'tt1266036',
    title: 'Valley Girl',
    originalTitle: 'Valley Girl',
    overview:
      "Set to a new wave '80s soundtrack, a pair of young lovers from different backgrounds defy their parents and friends to stay together.",
    runtime: 102,
    releaseDate: '2020-05-08',
    genres: ['Comedy', 'Music', 'Romance'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 6.741,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.7,
    ratingCount: 99,
    posterUrl: 'https://image.tmdb.org/t/p/w500/3ZdJN62RyjoQJ9S4zCbjtMQrYqE.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 28,
    tmdbId: 483157,
    imdbId: 'tt5726800',
    title: 'Morning Has Broken',
    originalTitle: 'Morning Has Broken',
    overview:
      'A young runaway girl moves in with a seemingly harmless, elderly, Academy Award-winning songwriter. It all seems perfectly normal, until his dark side unleashes a chain reaction of ghastly events.',
    runtime: 0,
    releaseDate: '2020-05-09',
    genres: ['Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.057,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500None',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 29,
    tmdbId: 487674,
    imdbId: 'tt6559576',
    title: 'Selfie Dad',
    originalTitle: 'Selfie Dad',
    overview:
      "Spiraling into a mid-life crisis and feeling disconnected from his family, Ben Marcus, a reality-TV editor, thinks he can only be happy by fulfilling his dream of becoming a professional comedian. Ben posts his stand-up routines to YouTube, and the videos fall flat. Then his tweener son posts Ben miserably failing on a home improvement project, and much to his teenage daughter's dismay, it goes viral, launching Ben's social-media career as Selfie Dad. Although he quickly becomes an award-winning phenom, no amount of success brings Ben satisfaction. Through his friendship with a young coworker, Mickey, Ben finds the secret to a happy family . . . with his Bible in one hand, and his phone in the other.",
    runtime: 97,
    releaseDate: '2020-06-19',
    genres: ['Comedy', 'Family'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.563,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.6,
    ratingCount: 12,
    posterUrl: 'https://image.tmdb.org/t/p/w500/xPhqit1DmfsAgC2i4HhZCCXUZW1.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 30,
    tmdbId: 510937,
    imdbId: 'tt4626020',
    title: 'The Bone Box',
    originalTitle: 'The Bone Box',
    overview:
      "Depressed and reeling from the recent death of his wife, Tom has built up quite a gambling debt. He goes to stay with his wealthy Aunt Florence in hopes that she will write him into her will. When a nasty creditor makes it clear that Tom is out of time, he devises a plan with Elodie, the undertaker's daughter, to rob the graves of the rich townspeople buried in the cemetery across the road. After plundering the graves, Tom arrives back at Florence's house and events take a dark turn. Tom begins hearing and seeing strange things that seem to coincide with the deaths of the people he robbed. Even more disconcerting... he appears to be the only one sensing the occurrences. One question lingers: Is Tom's conscience playing a trick on him... or is he really being haunted by those he stole from?",
    runtime: 86,
    releaseDate: '2020-06-15',
    genres: ['Drama', 'Horror', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.281,
    budget: 0,
    revenue: 0,
    ratingAverage: 3,
    ratingCount: 4,
    posterUrl: 'https://image.tmdb.org/t/p/w500/7taTVq6IXT8RnzwcRvonP9QULVu.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 31,
    tmdbId: 514593,
    imdbId: 'tt8201852',
    title: 'You Should Have Left',
    originalTitle: 'You Should Have Left',
    overview:
      'In an effort to repair their relationship, a couple books a vacation in the countryside for themselves and their daughter. What starts as a perfect retreat begins to fall apart as one loses their grip on reality, and a sinister force tries to tear them apart.',
    runtime: 93,
    releaseDate: '2020-06-18',
    genres: ['Horror', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 35.778,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.996,
    ratingCount: 800,
    posterUrl: 'https://image.tmdb.org/t/p/w500/tpOwE6xsWnu4lKeKbKW0R3iClM.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 32,
    tmdbId: 531876,
    imdbId: 'tt3833480',
    title: 'The Outpost',
    originalTitle: 'The Outpost',
    overview:
      'A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.',
    runtime: 123,
    releaseDate: '2020-06-24',
    genres: ['Action', 'Drama', 'History', 'War'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 12.865,
    budget: 18000000,
    revenue: 2133452,
    ratingAverage: 6.9,
    ratingCount: 1054,
    posterUrl: 'https://image.tmdb.org/t/p/w500/saN1UywIQMQNXYx2ag9j2tPwaVl.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 33,
    tmdbId: 520946,
    imdbId: 'tt8774798',
    title: '100% Wolf',
    originalTitle: '100% Wolf',
    overview:
      "Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle.  The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever.  With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.",
    runtime: 96,
    releaseDate: '2020-06-26',
    genres: ['Adventure', 'Animation', 'Family', 'Fantasy'],
    country: ['Australia', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 7.62,
    budget: 0,
    revenue: 9750139,
    ratingAverage: 6.1,
    ratingCount: 307,
    posterUrl: 'https://image.tmdb.org/t/p/w500/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 34,
    tmdbId: 521026,
    imdbId: 'tt7400952',
    title: 'Vampire Dad',
    originalTitle: 'Vampire Dad',
    overview:
      'In the early 1960s, a family man-turned-vampire struggles with his beastly nature while his devoted wife tries to keep anyone from finding out, including their teenage daughter.',
    runtime: 80,
    releaseDate: '2020-06-16',
    genres: ['Comedy', 'Fantasy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.925,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.7,
    ratingCount: 9,
    posterUrl: 'https://image.tmdb.org/t/p/w500/6I1Agpqqb7dkbZ0KawyrgcaRnvX.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 35,
    tmdbId: 521531,
    imdbId: 'tt5563782',
    title: 'Followed',
    originalTitle: 'Followed',
    overview:
      "Social media influencer, 'DropTheMike', seeks thrills and stardom in the most horrific places. When he's offered the possibility of a lucrative sponsorship, he takes his online channel to one of the most haunted hotels in America. What begins as a fun challenge accompanied by friends descends into a personal hell, begging the timely question: how far would you go to pursue internet fame?",
    runtime: 96,
    releaseDate: '2020-06-19',
    genres: ['Horror', 'Mystery', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 4.012,
    budget: 0,
    revenue: 548608,
    ratingAverage: 6.1,
    ratingCount: 81,
    posterUrl: 'https://image.tmdb.org/t/p/w500/cqQ7Fw21E5CMaGuyomh9E4crqZq.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 36,
    tmdbId: 522098,
    imdbId: 'tt8399664',
    title: 'Babyteeth',
    originalTitle: 'Babyteeth',
    overview:
      'A terminally ill teen upsets her parents when she falls in love with a small-time drug dealer.',
    runtime: 118,
    releaseDate: '2020-06-15',
    genres: ['Comedy', 'Drama', 'Romance'],
    country: ['Australia'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.118,
    budget: 0,
    revenue: 989310,
    ratingAverage: 6.9,
    ratingCount: 353,
    posterUrl: 'https://image.tmdb.org/t/p/w500/aINpljdt3VVMrCLtJW4BektwYOp.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 37,
    tmdbId: 523977,
    imdbId: 'tt6841122',
    title: 'Summerland',
    originalTitle: 'Summerland',
    overview:
      'A woman during the Second World War opens her heart to an evacuee after initially resolving to be rid of him.',
    runtime: 100,
    releaseDate: '2020-07-24',
    genres: ['Drama', 'Romance'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 7.331,
    budget: 0,
    revenue: 504296,
    ratingAverage: 7.5,
    ratingCount: 208,
    posterUrl: 'https://image.tmdb.org/t/p/w500/HEPZ2bF7Q3j9DUUsgfKxR1X4p2.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 38,
    tmdbId: 524047,
    imdbId: 'tt7737786',
    title: 'Greenland',
    originalTitle: 'Greenland',
    overview:
      'John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garritys experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.',
    runtime: 120,
    releaseDate: '2020-07-29',
    genres: ['Action', 'Thriller'],
    country: ['United Kingdom', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 49.766,
    budget: 34000000,
    revenue: 52300000,
    ratingAverage: 7.1,
    ratingCount: 4608,
    posterUrl: 'https://image.tmdb.org/t/p/w500/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 39,
    tmdbId: 526973,
    imdbId: 'tt1656177',
    title: 'Target Number One',
    originalTitle: 'Target Number One',
    overview:
      'Ex heroin junkie, Daniel Léger, gets involved in a drug deal with the wrong people for the wrong reasons. When the deal goes sour, Daniel gets thrown into a Thai prison and slapped with a 100-year sentence. While he tries to survive his Bangkok incarceration, the news of his conviction captures the attention of Globe and Mail journalist Victor Malarek, who decides to go after the shady undercover cops responsible for wrongly accusing Daniel.',
    runtime: 135,
    releaseDate: '2020-07-10',
    genres: ['Crime', 'Thriller'],
    country: ['Canada', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.546,
    budget: 138000,
    revenue: 0,
    ratingAverage: 6.3,
    ratingCount: 122,
    posterUrl: 'https://image.tmdb.org/t/p/w500/wb2VpOZTSINPI7jQww0fYCEppcE.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 40,
    tmdbId: 527660,
    imdbId: 'tt8949056',
    title: 'Yes, God, Yes',
    originalTitle: 'Yes, God, Yes',
    overview:
      'Alice, a young innocent Catholic girl, is tempted into masturbating after an AOL chat suddenly turns sexual, however is conflicted as the act would be considered a sin.',
    runtime: 78,
    releaseDate: '2020-07-24',
    genres: ['Comedy', 'Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 9.398,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.3,
    ratingCount: 536,
    posterUrl: 'https://image.tmdb.org/t/p/w500/69SYznq2mSbgKyQF3QHYwblmqAk.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 41,
    tmdbId: 539181,
    imdbId: 'tt9072352',
    title: 'Relic',
    originalTitle: 'Relic',
    overview:
      "When elderly mother Edna inexplicably vanishes, her daughter rushes to the family's decaying home, finding clues of her increasing dementia scattered around the house in her absence.",
    runtime: 89,
    releaseDate: '2020-07-03',
    genres: ['Horror', 'Mystery'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 6.63,
    budget: 1229578,
    revenue: 3238539,
    ratingAverage: 6.1,
    ratingCount: 749,
    posterUrl: 'https://image.tmdb.org/t/p/w500/3wZ0gxLqsPleneFSTZILmM3BE8Q.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 42,
    tmdbId: 539885,
    imdbId: 'tt8784956',
    title: 'Ava',
    originalTitle: 'Ava',
    overview:
      'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
    runtime: 96,
    releaseDate: '2020-07-02',
    genres: ['Action', 'Crime', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 13.634,
    budget: 0,
    revenue: 2987741,
    ratingAverage: 5.835,
    ratingCount: 2608,
    posterUrl: 'https://image.tmdb.org/t/p/w500/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 43,
    tmdbId: 544859,
    imdbId: 'tt8526344',
    title: 'Juvenile Delinquents',
    originalTitle: 'Juvenile Delinquents',
    overview:
      'Broken teens facing incarceration for a crime they were forced to commit decide not to accept their destitute destiny and go about making a new one by forcing redemption onto bad people. The Juvenile Delinquents form a new dysfunctional family as they maneuver around problems manifesting from their youth, competitiveness, irrationality, and the gruesomeness of their new lives.',
    runtime: 118,
    releaseDate: '2020-07-30',
    genres: ['Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.751,
    budget: 240000,
    revenue: 0,
    ratingAverage: 4.7,
    ratingCount: 3,
    posterUrl: 'https://image.tmdb.org/t/p/w500/mwzA0B65a3CIdZckHnpfNEWevMT.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 44,
    tmdbId: 547016,
    imdbId: 'tt7556122',
    title: 'The Old Guard',
    originalTitle: 'The Old Guard',
    overview:
      "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
    runtime: 125,
    releaseDate: '2020-07-10',
    genres: ['Action', 'Fantasy'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 17.052,
    budget: 70000000,
    revenue: 0,
    ratingAverage: 7.136,
    ratingCount: 4230,
    posterUrl: 'https://image.tmdb.org/t/p/w500/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 45,
    tmdbId: 1094611,
    imdbId: null,
    title: 'The Great Heist',
    originalTitle: 'The Great Heist',
    overview:
      'Three cowboys lose themselves in desert. On the run, they are confronted by evil forces that make them question themselves and their surroundings.',
    runtime: 55,
    releaseDate: '2020-08-28',
    genres: ['Comedy', 'Western'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.313,
    budget: 1000,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/6DTWOgQWtE6Q5jewSpBnhUDtGgu.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 46,
    tmdbId: 552835,
    imdbId: 'tt3453008',
    title: 'The Garden Left Behind',
    originalTitle: 'The Garden Left Behind',
    overview:
      "Traces the relationship between Tina, a young Mexican trans woman, and Eliana, her grandmother, as they navigate Tina's transition and struggle to build a life for themselves as undocumented immigrants in New York City.",
    runtime: 88,
    releaseDate: '2020-08-28',
    genres: ['Drama'],
    country: ['Brazil', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.797,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.9,
    ratingCount: 5,
    posterUrl: 'https://image.tmdb.org/t/p/w500/wNGXT2aIiswaY9blHQwowWV8MXq.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 47,
    tmdbId: 577922,
    imdbId: 'tt6723592',
    title: 'Tenet',
    originalTitle: 'Tenet',
    overview:
      'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
    runtime: 150,
    releaseDate: '2020-08-22',
    genres: ['Action', 'Science Fiction', 'Thriller'],
    country: ['United Kingdom', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 27.862,
    budget: 205000000,
    revenue: 365304105,
    ratingAverage: 7.2,
    ratingCount: 10070,
    posterUrl: 'https://image.tmdb.org/t/p/w500/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 48,
    tmdbId: 578944,
    imdbId: 'tt7343740',
    title: 'Days of the Bagnold Summer',
    originalTitle: 'Days of the Bagnold Summer',
    overview:
      "Sue works in a library. Daniel eats crisps and listens to Metallica. This was the summer Daniel was due to spend with his father and his father's new wife in Florida. But when they cancel his trip at the last minute, Sue and Daniel suddenly face the prospect of six long weeks together.",
    runtime: 86,
    releaseDate: '2020-08-13',
    genres: ['Comedy'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 2.744,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.074,
    ratingCount: 54,
    posterUrl: 'https://image.tmdb.org/t/p/w500/8pLGR2AGdxwKy8kNuLfs1t7wNX.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 49,
    tmdbId: 582300,
    imdbId: 'tt6269308',
    title: 'The Bellwether',
    originalTitle: 'The Bellwether',
    overview:
      "To the outside world Joanne is just a book-store owner, but the Conspiracy knows different. She's dangerous. She's a bellwether: a quiet leader who is well on her way to being her whole self. When they kidnap her to break her to make her conform, they discover that Joanne is something so much more than even she ever knew. Joanne is a feminist, one-room, one-character elevated genre thriller. It is a modern rite of passage story which most women have to go through to become a whole human being: How does one be oneself in the face of massive misogyny and hatred (both overt and institutionalized). It is also the world's first one-person film (a movie with only one on-screen character) that features a woman.",
    runtime: 71,
    releaseDate: '2020-08-20',
    genres: ['Drama', 'Horror', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.42,
    budget: 0,
    revenue: 0,
    ratingAverage: 7,
    ratingCount: 3,
    posterUrl: 'https://image.tmdb.org/t/p/w500/iaFxlT8dR8VdrGiw0mSeBQFWKDS.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 50,
    tmdbId: 585013,
    imdbId: 'tt7290030',
    title: "#Shakespeare's Shitstorm",
    originalTitle: "#Shakespeare's Shitstorm",
    overview:
      'Mad scientist Prospero runs away with his blind daughter Miranda to Tromaville, hiding from evil pharmaceutical execs, including his own sister Antoinette who ruined his career after he found the cure against opioid addiction. With the help of a handicapped crack-whore, he releases a massive amount of laxative to whales, while his enemies are on a cruise ship to North Korea. A humongous shitstorm washes the boat away and brings them to Tromaville, where Prospero can now fully realize his ultimate vengeance.',
    runtime: 94,
    releaseDate: '2020-08-20',
    genres: ['Comedy', 'Horror'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.856,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.7,
    ratingCount: 7,
    posterUrl: 'https://image.tmdb.org/t/p/w500/chAsvI8qgZAOKFUceFZRLz52fVS.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 51,
    tmdbId: 589877,
    imdbId: 'tt8740332',
    title: 'The Good Things Devils Do',
    originalTitle: 'The Good Things Devils Do',
    overview:
      "It was supposed to be one last heist but it shouldn't be a surprise that a burglary in Transylvania County would be interrupted by an ancient vampire's awakening, resulting in a night of terror.",
    runtime: 81,
    releaseDate: '2020-08-15',
    genres: ['Horror'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.032,
    budget: 0,
    revenue: 0,
    ratingAverage: 4.6,
    ratingCount: 12,
    posterUrl: 'https://image.tmdb.org/t/p/w500/tSFEF9zVV64ko1F3Hj24mrUsPT2.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 52,
    tmdbId: 594328,
    imdbId: 'tt1817232',
    title: 'Phineas and Ferb the Movie: Candace Against the Universe',
    originalTitle: 'Phineas and Ferb the Movie: Candace Against the Universe',
    overview:
      'Phineas and Ferb travel across the galaxy to rescue their older sister Candace, who has been abducted by aliens and taken to a utopia in a far-off planet, free of her pesky little brothers.',
    runtime: 85,
    releaseDate: '2020-08-27',
    genres: ['Animation', 'Comedy', 'Family', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 9.89,
    budget: 0,
    revenue: 0,
    ratingAverage: 7.261,
    ratingCount: 373,
    posterUrl: 'https://image.tmdb.org/t/p/w500/afOa3CpPffC3uQCH2fhMaO3AYpB.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 53,
    tmdbId: 1096391,
    imdbId: 'tt13062492',
    title: 'Nonstop Flight: The Untold Story of FC Cincinnati',
    originalTitle: 'Nonstop Flight: The Untold Story of FC Cincinnati',
    overview: 'How FC Cincinnati went from a third-division team to Major League Soccer.',
    runtime: 100,
    releaseDate: '2020-09-09',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.185,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/f2WY7RRaLgfngoOS1V7RX5SB6Lw.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 54,
    tmdbId: 1096847,
    imdbId: 'tt12261768',
    title: 'Soul Forest',
    originalTitle: 'Soul Forest',
    overview:
      'Soul Forest takes on an ambitious storyline set in a dystopian future. It follows four main characters who have been placed into a realistic Virtual Simulation as part of a new programme for prison inmates seeking parole.',
    runtime: 15,
    releaseDate: '2020-09-01',
    genres: ['Thriller'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.171,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/2sSsARjGbizjKU1U11ZWrZb2ylg.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 55,
    tmdbId: 597156,
    imdbId: 'tt10199914',
    title: 'The Boys in the Band',
    originalTitle: 'The Boys in the Band',
    overview:
      'At a birthday party in 1968 New York, a surprise guest and a drunken game leave seven gay friends reckoning with unspoken feelings and buried truths.',
    runtime: 121,
    releaseDate: '2020-09-30',
    genres: ['Drama'],
    country: ['Canada', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.239,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.811,
    ratingCount: 429,
    posterUrl: 'https://image.tmdb.org/t/p/w500/oHJnXabEr07fR85if5ykISkqflr.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 56,
    tmdbId: 601260,
    imdbId: 'tt8629592',
    title: 'Last Call',
    originalTitle: 'Last Call',
    overview:
      "Last Call follows a suicidal alcoholic on the anniversary of his son's death. When he attempts to call a crisis hotline, a misdial connects him with a single mother working as the night janitor at a local community college.",
    runtime: 77,
    releaseDate: '2020-09-18',
    genres: ['Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.875,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.4,
    ratingCount: 8,
    posterUrl: 'https://image.tmdb.org/t/p/w500/1p7LeD1u6rbaC0agvIkrf0yLlQc.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 57,
    tmdbId: 605499,
    imdbId: 'tt8090564',
    title: 'Monsoon',
    originalTitle: 'Monsoon',
    overview:
      "Kit can't remember much of his native Vietnam. When he returns to the Land of the Golden Star for the first time in over thirty years, he takes in his local surroundings as any Western tourist would, and the environment is as exotic as the language is incomprehensible. The aim of Kit's travels – to find a place to scatter his parents' ashes – thus becomes part of a journey back to his roots and to the discovery of his identity, which external circumstances have rendered ambiguous and complex.",
    runtime: 85,
    releaseDate: '2020-09-25',
    genres: ['Drama', 'Romance'],
    country: ['United Kingdom'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.993,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.5,
    ratingCount: 35,
    posterUrl: 'https://image.tmdb.org/t/p/w500/xIKVeH1iAKJOYYh9lvObD3hYIaf.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 58,
    tmdbId: 606876,
    imdbId: 'tt8593904',
    title: "Rifkin's Festival",
    originalTitle: "Rifkin's Festival",
    overview:
      'The story of a married American couple who go to the San Sebastian Film Festival. They get caught up in the magic of the festival, the beauty and charm of Spain and the fantasy of movies. She has an affair with a brilliant French movie director, and he falls in love with a beautiful Spanish woman who lives there.',
    runtime: 92,
    releaseDate: '2020-10-01',
    genres: ['Comedy', 'Romance'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.62,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.1,
    ratingCount: 435,
    posterUrl: 'https://image.tmdb.org/t/p/w500/5kTkLEheDmXdnHHRJiAkd4Vuato.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 59,
    tmdbId: 606903,
    imdbId: 'tt6222828',
    title: 'Monster Force Zero',
    originalTitle: 'Monster Force Zero',
    overview:
      "A group of sci-fi cosplayers are granted superpowers and are transported into the multiverse to do real battle with evil alien forces bent on Earth's destruction.",
    runtime: 82,
    releaseDate: '2020-10-01',
    genres: ['Action', 'Comedy', 'Science Fiction'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.597,
    budget: 0,
    revenue: 0,
    ratingAverage: 0.8,
    ratingCount: 3,
    posterUrl: 'https://image.tmdb.org/t/p/w500/7J1iXXA5PsGxff8TDLBfjqGI7xt.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 60,
    tmdbId: 610069,
    imdbId: 'tt3165282',
    title: 'Killer Weekend',
    originalTitle: 'Killer Weekend',
    overview:
      'A sexy young coed enjoys a lavish lifestyle thanks to a sugar daddy dating app, accessing their money by having them killed. She soon meets her match, however, in her new rich, handsome boyfriend - who happens to also be a serial killer.',
    runtime: 90,
    releaseDate: '2020-10-26',
    genres: ['Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.665,
    budget: 0,
    revenue: 0,
    ratingAverage: 4.9,
    ratingCount: 9,
    posterUrl: 'https://image.tmdb.org/t/p/w500/iyzMeofrUVYyiPoItBcKjRgxlIh.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 61,
    tmdbId: 610076,
    imdbId: null,
    title: 'Beautiful and Pitiless',
    originalTitle: 'Beautiful and Pitiless',
    overview:
      'A hike in the wilderness turns ugly when the mysterious forest has a couple of surprises.',
    runtime: 96,
    releaseDate: '2020-10-30',
    genres: ['Horror'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.049,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500None',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 62,
    tmdbId: 610359,
    imdbId: 'tt6580050',
    title: 'On Halloween',
    originalTitle: 'On Halloween',
    overview:
      'A journalist goes in search of the truth after a series of brutal deaths and disappearances lead back to an urban legend about a serial killing clown that has stalked the woods of Century Park for over a hundred years.',
    runtime: 92,
    releaseDate: '2020-10-09',
    genres: ['Horror', 'Thriller'],
    country: ['Australia', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 2.534,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.3,
    ratingCount: 50,
    posterUrl: 'https://image.tmdb.org/t/p/w500/5rsEhgcNRUthjo6fqRDqZy5plx.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 63,
    tmdbId: 611114,
    imdbId: 'tt9731360',
    title: 'I Met a Girl',
    originalTitle: 'I Met a Girl',
    overview:
      'An impulsive musician struggling with schizophrenia falls for a mysterious woman who may be all in his head. When she suddenly vanishes, he takes off on a cross- country journey across Australia to find her, forcing his long-suffering brother to try to rescue him.',
    runtime: 108,
    releaseDate: '2020-11-26',
    genres: ['Comedy', 'Drama', 'Romance'],
    country: ['Australia', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 4.189,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.3,
    ratingCount: 48,
    posterUrl: 'https://image.tmdb.org/t/p/w500/1ciFilxT0XaVhgjeKviA9FMP9Nu.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 64,
    tmdbId: 614560,
    imdbId: 'tt10618286',
    title: 'Mank',
    originalTitle: 'Mank',
    overview:
      '1930s Hollywood is reevaluated through the eyes of scathing social critic and alcoholic screenwriter Herman J. Mankiewicz as he races to finish the screenplay of Citizen Kane.',
    runtime: 132,
    releaseDate: '2020-11-13',
    genres: ['Drama', 'History'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 8.706,
    budget: 25000000,
    revenue: 122252,
    ratingAverage: 6.68,
    ratingCount: 1624,
    posterUrl: 'https://image.tmdb.org/t/p/w500/4yzTcAtvzyZLLto4z04xobUK9el.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 65,
    tmdbId: 615667,
    imdbId: 'tt10514222',
    title: "Ma Rainey's Black Bottom",
    originalTitle: "Ma Rainey's Black Bottom",
    overview:
      "Tensions rise when the trailblazing Mother of the Blues and her band gather at a Chicago recording studio in 1927. Adapted from August Wilson's play.",
    runtime: 94,
    releaseDate: '2020-11-25',
    genres: ['Drama', 'Music'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.918,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.658,
    ratingCount: 1166,
    posterUrl: 'https://image.tmdb.org/t/p/w500/pvtyxijaBrCSbByXLcUIDDSvc40.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 66,
    tmdbId: 618798,
    imdbId: 'tt9667668',
    title: 'Caramel',
    originalTitle: 'Caramel',
    overview:
      "A teenager comes to terms with his place in the world when he learns of his mother's immoral past the day before his grandfather's funeral.",
    runtime: 14,
    releaseDate: '2020-11-05',
    genres: ['Comedy', 'Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.244,
    budget: 10000,
    revenue: 0,
    ratingAverage: 7,
    ratingCount: 1,
    posterUrl: 'https://image.tmdb.org/t/p/w500/7mYQ0GpbIhz9peNTFThks6rXqIA.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 67,
    tmdbId: 622855,
    imdbId: 'tt7736496',
    title: 'Jingle Jangle: A Christmas Journey',
    originalTitle: 'Jingle Jangle: A Christmas Journey',
    overview:
      'An imaginary world comes to life in a holiday tale of an eccentric toymaker, his adventurous granddaughter, and a magical invention that has the power to change their lives forever.',
    runtime: 122,
    releaseDate: '2020-11-06',
    genres: ['Family', 'Fantasy', 'Music'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 6.949,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.6,
    ratingCount: 526,
    posterUrl: 'https://image.tmdb.org/t/p/w500/5RbyHIVydD3Krmec1LlUV7rRjet.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 68,
    tmdbId: 623238,
    imdbId: 'tt7156898',
    title: 'County Lines',
    originalTitle: 'County Lines',
    overview:
      "A powerful drama about a mother and her fourteen year old boy who is groomed into a lethal nationwide drug selling enterprise, a 'County Line', which exploits vulnerable children and traffics them across Britain.",
    runtime: 90,
    releaseDate: '2020-12-04',
    genres: ['Drama'],
    country: ['United Kingdom', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.426,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.862,
    ratingCount: 29,
    posterUrl: 'https://image.tmdb.org/t/p/w500/odYS1rnUj1K60rRmfAl1MJC9nP6.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 69,
    tmdbId: 623856,
    imdbId: 'tt10808832',
    title: 'Let Them All Talk',
    originalTitle: 'Let Them All Talk',
    overview:
      'A celebrated author takes a journey with some old friends to have some fun and heal old wounds. Her nephew comes along to wrangle the ladies and finds himself involved with a young literary agent.',
    runtime: 113,
    releaseDate: '2020-12-10',
    genres: ['Comedy', 'Drama'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.963,
    budget: 0,
    revenue: 0,
    ratingAverage: 5.6,
    ratingCount: 254,
    posterUrl: 'https://image.tmdb.org/t/p/w500/4mhZqZ7nXL6Dj6PKZSseJxv1qXZ.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 70,
    tmdbId: 624788,
    imdbId: 'tt9601220',
    title: 'Black Bear',
    originalTitle: 'Black Bear',
    overview:
      'At a remote lake house in the Adirondack Mountains, a couple entertains an out-of-town guest looking for inspiration in her filmmaking. The group quickly falls into a calculated game of desire, manipulation, and jealousy, unaware of how dangerously intertwined their lives will soon become.',
    runtime: 106,
    releaseDate: '2020-12-04',
    genres: ['Drama', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 5.124,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.464,
    ratingCount: 263,
    posterUrl: 'https://image.tmdb.org/t/p/w500/nqZFjQRWfW6PjFTc17pzJ5LRAAv.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 71,
    tmdbId: 625342,
    imdbId: 'tt10313876',
    title: 'The Art of Political Murder',
    originalTitle: 'The Art of Political Murder',
    overview:
      "An investigation into the truth behind the murder of Guatemalan Bishop, Juan Gerardi, who was killed in 1998 just days after trying to hold the country's military accountable for the atrocities committed during its civil war.",
    runtime: 89,
    releaseDate: '2020-12-16',
    genres: ['Documentary'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.157,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.8,
    ratingCount: 6,
    posterUrl: 'https://image.tmdb.org/t/p/w500/ybe9eyjxa8j9FCJdPNLDV5FGOyt.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 72,
    tmdbId: 627103,
    imdbId: 'tt10235718',
    title: 'Love, Weddings & Other Disasters',
    originalTitle: 'Love, Weddings & Other Disasters',
    overview:
      'A fussy celebrity caterer, a blind woman, a tour-bus guide and an inexperienced wedding planner search for love.',
    runtime: 96,
    releaseDate: '2020-12-04',
    genres: ['Comedy', 'Romance'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 3.077,
    budget: 0,
    revenue: 0,
    ratingAverage: 6,
    ratingCount: 75,
    posterUrl: 'https://image.tmdb.org/t/p/w500/8P1H3tmf7o322agBGsdVFRP84aG.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 73,
    tmdbId: 628534,
    imdbId: 'tt6571548',
    title: 'The White Tiger',
    originalTitle: 'The White Tiger',
    overview:
      'An ambitious Indian driver uses his wit and cunning to escape from poverty and rise to the top. An epic journey based on the New York Times bestseller.',
    runtime: 125,
    releaseDate: '2021-01-13',
    genres: ['Drama'],
    country: ['Singapore', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 7.347,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.964,
    ratingCount: 894,
    posterUrl: 'https://image.tmdb.org/t/p/w500/5JnmseS3DZ6ad2VMbrnbGCs8Rst.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 74,
    tmdbId: 630586,
    imdbId: 'tt9110170',
    title: 'Wrong Turn',
    originalTitle: 'Wrong Turn',
    overview:
      'Jen and a group of friends set out to hike the Appalachian Trail. Despite warnings to stick to the trail, the hikers stray off course—and cross into land inhabited by The Foundation, a hidden community of mountain dwellers who use deadly means to protect their way of life.',
    runtime: 110,
    releaseDate: '2021-01-26',
    genres: ['Horror', 'Thriller'],
    country: ['United Kingdom', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 28.715,
    budget: 0,
    revenue: 3777969,
    ratingAverage: 5.976,
    ratingCount: 1167,
    posterUrl: 'https://image.tmdb.org/t/p/w500/4U1SBHmwHkNA0eHZ2n1CuiC1K1g.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 75,
    tmdbId: 630926,
    imdbId: 'tt11363582',
    title: "A New Year's Resolution",
    originalTitle: "A New Year's Resolution",
    overview:
      "When a morning show producer makes a New Year's resolution to say yes more, she crosses paths with a confirmed Yes man who just might hold the key to her biggest story and to her heart.",
    runtime: 85,
    releaseDate: '2021-01-09',
    genres: ['Romance', 'TV Movie'],
    country: ['Canada', 'United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 1.749,
    budget: 0,
    revenue: 0,
    ratingAverage: 6.3,
    ratingCount: 31,
    posterUrl: 'https://image.tmdb.org/t/p/w500/l9l1v24dqbAlHdYHpt9T84zs17J.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 76,
    tmdbId: 1376469,
    imdbId: 'tt13506734',
    title: 'Wings of Hope - A story of Bravery',
    originalTitle: 'Wings of Hope - A story of Bravery',
    overview:
      'This documentary takes us back to...  ...the troubled days of 1943. A team of young airmen, of the allied forces, is being shot down out the coast of Sifnos. They manage to reach the island and get rescued by the locals. We will get to know our heroes, through the eyes of their descendants and know about their actions that echo to our days.',
    runtime: 33,
    releaseDate: '2021-01-15',
    genres: ['Documentary'],
    country: ['Greece'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 0.015,
    budget: 0,
    revenue: 0,
    ratingAverage: 0,
    ratingCount: 0,
    posterUrl: 'https://image.tmdb.org/t/p/w500/17LuDgqEra4lNaAKMIjKc5sWn55.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
  {
    id: 77,
    tmdbId: 634528,
    imdbId: 'tt6902332',
    title: 'The Marksman',
    originalTitle: 'The Marksman',
    overview: `Jim Hanson''s quiet life is suddenly disturbed by two people crossing the US/Mexico border, a woman and her young son, desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy''s reluctant defender. He embraces his role as Miguel''s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.`,
    runtime: 108,
    releaseDate: '2021-01-15',
    genres: ['Action', 'Drama', 'Thriller'],
    country: ['United States of America'],
    language: 'English',
    movieStatus: 'Released',
    popularity: 16.783,
    budget: 23000000,
    revenue: 23076711,
    ratingAverage: 6.8,
    ratingCount: 1613,
    posterUrl: 'https://image.tmdb.org/t/p/w500/6vcDalR50RWa309vBH1NLmG2rjQ.jpg',
    rentalRate: 11.0,
    rentalDuration: 3,
  },
];
