export enum COUNTRIES {
  AF = 'Afghanistan',
  AL = 'Albania',
  DZ = 'Algeria',
  AS = 'American Samoa',
  AD = 'Andorra',
  AO = 'Angola',
  AI = 'Anguilla',
  AQ = 'Antarctica',
  AG = 'Antigua and Barbuda',
  AR = 'Argentina',
  AM = 'Armenia',
  AW = 'Aruba',
  AU = 'Australia',
  AT = 'Austria',
  AZ = 'Azerbaijan',
  BS = 'Bahamas',
  BH = 'Bahrain',
  BD = 'Bangladesh',
  BB = 'Barbados',
  BY = 'Belarus',
  BE = 'Belgium',
  BZ = 'Belize',
  BJ = 'Benin',
  BM = 'Bermuda',
  BT = 'Bhutan',
  BO = 'Bolivia',
  BA = 'Bosnia and Herzegovina',
  BW = 'Botswana',
  BV = 'Bouvet Island',
  BR = 'Brazil',
  IO = 'British Indian Ocean Territory',
  VG = 'British Virgin Islands',
  BN = 'Brunei Darussalam',
  BG = 'Bulgaria',
  BF = 'Burkina Faso',
  BU = 'Burma',
  BI = 'Burundi',
  KH = 'Cambodia',
  CM = 'Cameroon',
  CA = 'Canada',
  CV = 'Cape Verde',
  KY = 'Cayman Islands',
  CF = 'Central African Republic',
  TD = 'Chad',
  CL = 'Chile',
  CN = 'China',
  CX = 'Christmas Island',
  CC = 'Cocos  Islands',
  CO = 'Colombia',
  KM = 'Comoros',
  CD = 'Democratic Republic of the Congo (Kinshasa)',
  CG = 'Republic of the Congo (Brazzaville)',
  CK = 'Cook Islands',
  CR = 'Costa Rica',
  CI = "Cote D'Ivoire",
  HR = 'Croatia',
  CU = 'Cuba',
  CY = 'Cyprus',
  CZ = 'Czech Republic',
  XC = 'Czechoslovakia',
  DK = 'Denmark',
  DJ = 'Djibouti',
  DM = 'Dominica',
  DO = 'Dominican Republic',
  XG = 'East Germany',
  TP = 'East Timor',
  EC = 'Ecuador',
  EG = 'Egypt',
  SV = 'El Salvador',
  GQ = 'Equatorial Guinea',
  ER = 'Eritrea',
  EE = 'Estonia',
  ET = 'Ethiopia',
  FO = 'Faeroe Islands',
  FK = 'Falkland Islands',
  FJ = 'Fiji',
  FI = 'Finland',
  FR = 'France',
  GF = 'French Guiana',
  PF = 'French Polynesia',
  TF = 'French Southern Territories',
  GA = 'Gabon',
  GM = 'Gambia',
  GE = 'Georgia',
  DE = 'Germany',
  GH = 'Ghana',
  GI = 'Gibraltar',
  GR = 'Greece',
  GL = 'Greenland',
  GD = 'Grenada',
  GP = 'Guadaloupe',
  GU = 'Guam',
  GT = 'Guatemala',
  GN = 'Guinea',
  GW = 'Guinea-Bissau',
  GY = 'Guyana',
  HT = 'Haiti',
  HM = 'Heard and McDonald Islands',
  VA = 'Holy See',
  HN = 'Honduras',
  HK = 'Hong Kong',
  HU = 'Hungary',
  IS = 'Iceland',
  IN = 'India',
  ID = 'Indonesia',
  IR = 'Iran',
  IQ = 'Iraq',
  IE = 'Ireland',
  IL = 'Israel',
  IT = 'Italy',
  JM = 'Jamaica',
  JP = 'Japan',
  JO = 'Jordan',
  KZ = 'Kazakhstan',
  KE = 'Kenya',
  KI = 'Kiribati',
  XK = 'Kosovo',
  KW = 'Kuwait',
  KG = 'Kyrgyz Republic',
  LA = "Lao People's Democratic Republic",
  LV = 'Latvia',
  LB = 'Lebanon',
  LS = 'Lesotho',
  LR = 'Liberia',
  LY = 'Libyan Arab Jamahiriya',
  LI = 'Liechtenstein',
  LT = 'Lithuania',
  LU = 'Luxembourg',
  MO = 'Macao',
  MK = 'Macedonia',
  MG = 'Madagascar',
  MW = 'Malawi',
  MY = 'Malaysia',
  MV = 'Maldives',
  ML = 'Mali',
  MT = 'Malta',
  MH = 'Marshall Islands',
  MQ = 'Martinique',
  MR = 'Mauritania',
  MU = 'Mauritius',
  YT = 'Mayotte',
  MX = 'Mexico',
  FM = 'Micronesia',
  MD = 'Moldova',
  MC = 'Monaco',
  MN = 'Mongolia',
  ME = 'Montenegro',
  MS = 'Montserrat',
  MA = 'Morocco',
  MZ = 'Mozambique',
  MM = 'Myanmar',
  NA = 'Namibia',
  NR = 'Nauru',
  NP = 'Nepal',
  NL = 'Netherlands',
  AN = 'Netherlands Antilles',
  NC = 'New Caledonia',
  NZ = 'New Zealand',
  NI = 'Nicaragua',
  NE = 'Niger',
  NG = 'Nigeria',
  NU = 'Niue',
  NF = 'Norfolk Island',
  KP = 'North Korea',
  XI = 'Northern Ireland',
  MP = 'Northern Mariana Islands',
  NO = 'Norway',
  OM = 'Oman',
  PK = 'Pakistan',
  PW = 'Palau',
  PS = 'Palestinian Territory',
  PA = 'Panama',
  PG = 'Papua New Guinea',
  PY = 'Paraguay',
  PE = 'Peru',
  PH = 'Philippines',
  PN = 'Pitcairn Island',
  PL = 'Poland',
  PT = 'Portugal',
  PR = 'Puerto Rico',
  QA = 'Qatar',
  RE = 'Reunion',
  RO = 'Romania',
  RU = 'Russia',
  RW = 'Rwanda',
  WS = 'Samoa',
  SM = 'San Marino',
  ST = 'Sao Tome and Principe',
  SA = 'Saudi Arabia',
  SN = 'Senegal',
  RS = 'Serbia',
  CS = 'Serbia and Montenegro',
  SC = 'Seychelles',
  SL = 'Sierra Leone',
  SG = 'Singapore',
  SK = 'Slovakia',
  SI = 'Slovenia',
  SB = 'Solomon Islands',
  SO = 'Somalia',
  ZA = 'South Africa',
  GS = 'South Georgia and the South Sandwich Islands',
  KR = 'South Korea',
  SS = 'South Sudan',
  SU = 'Soviet Union',
  ES = 'Spain',
  LK = 'Sri Lanka',
  SH = 'St. Helena',
  KN = 'St. Kitts and Nevis',
  LC = 'St. Lucia',
  PM = 'St. Pierre and Miquelon',
  VC = 'St. Vincent and the Grenadines',
  SD = 'Sudan',
  SR = 'Suriname',
  SJ = 'Svalbard & Jan Mayen Islands',
  SZ = 'Swaziland',
  SE = 'Sweden',
  CH = 'Switzerland',
  SY = 'Syrian Arab Republic',
  TW = 'Taiwan',
  TJ = 'Tajikistan',
  TZ = 'Tanzania',
  TH = 'Thailand',
  TL = 'Timor-Leste',
  TG = 'Togo',
  TK = 'Tokelau',
  TO = 'Tonga',
  TT = 'Trinidad and Tobago',
  TN = 'Tunisia',
  TR = 'Turkey',
  TM = 'Turkmenistan',
  TC = 'Turks and Caicos Islands',
  TV = 'Tuvalu',
  VI = 'US Virgin Islands',
  UG = 'Uganda',
  UA = 'Ukraine',
  AE = 'United Arab Emirates',
  GB = 'United Kingdom',
  UM = 'United States Minor Outlying Islands',
  US = 'United States of America',
  UY = 'Uruguay',
  UZ = 'Uzbekistan',
  VU = 'Vanuatu',
  VE = 'Venezuela',
  VN = 'Vietnam',
  WF = 'Wallis and Futuna Islands',
  EH = 'Western Sahara',
  YE = 'Yemen',
  YU = 'Yugoslavia',
  ZR = 'Zaire',
  ZM = 'Zambia',
  ZW = 'Zimbabwe',
}

export const availableCountries: { [key: string]: number } = {
  AF: 1,
  AL: 2,
  DZ: 3,
  AS: 4,
  AD: 5,
  AO: 6,
  AI: 7,
  AQ: 8,
  AG: 9,
  AR: 10,
  AM: 11,
  AW: 12,
  AU: 13,
  AT: 14,
  AZ: 15,
  BS: 16,
  BH: 17,
  BD: 18,
  BB: 19,
  BY: 20,
  BE: 21,
  BZ: 22,
  BJ: 23,
  BM: 24,
  BT: 25,
  BO: 26,
  BA: 27,
  BW: 28,
  BV: 29,
  BR: 30,
  IO: 31,
  VG: 32,
  BN: 33,
  BG: 34,
  BF: 35,
  BU: 36,
  BI: 37,
  KH: 38,
  CM: 39,
  CA: 40,
  CV: 41,
  KY: 42,
  CF: 43,
  TD: 44,
  CL: 45,
  CN: 46,
  CX: 47,
  CC: 48,
  CO: 49,
  KM: 50,
  CD: 51,
  CG: 52,
  CK: 53,
  CR: 54,
  CI: 55,
  HR: 56,
  CU: 57,
  CY: 58,
  CZ: 59,
  XC: 60,
  DK: 61,
  DJ: 62,
  DM: 63,
  DO: 64,
  XG: 65,
  TP: 66,
  EC: 67,
  EG: 68,
  SV: 69,
  GQ: 70,
  ER: 71,
  EE: 72,
  ET: 73,
  FO: 74,
  FK: 75,
  FJ: 76,
  FI: 77,
  FR: 78,
  GF: 79,
  PF: 80,
  TF: 81,
  GA: 82,
  GM: 83,
  GE: 84,
  DE: 85,
  GH: 86,
  GI: 87,
  GR: 88,
  GL: 89,
  GD: 90,
  GP: 91,
  GU: 92,
  GT: 93,
  GN: 94,
  GW: 95,
  GY: 96,
  HT: 97,
  HM: 98,
  VA: 99,
  HN: 100,
  HK: 101,
  HU: 102,
  IS: 103,
  IN: 104,
  ID: 105,
  IR: 106,
  IQ: 107,
  IE: 108,
  IL: 109,
  IT: 110,
  JM: 111,
  JP: 112,
  JO: 113,
  KZ: 114,
  KE: 115,
  KI: 116,
  XK: 117,
  KW: 118,
  KG: 119,
  LA: 120,
  LV: 121,
  LB: 122,
  LS: 123,
  LR: 124,
  LY: 125,
  LI: 126,
  LT: 127,
  LU: 128,
  MO: 129,
  MK: 130,
  MG: 131,
  MW: 132,
  MY: 133,
  MV: 134,
  ML: 135,
  MT: 136,
  MH: 137,
  MQ: 138,
  MR: 139,
  MU: 140,
  YT: 141,
  MX: 142,
  FM: 143,
  MD: 144,
  MC: 145,
  MN: 146,
  ME: 147,
  MS: 148,
  MA: 149,
  MZ: 150,
  MM: 151,
  NA: 152,
  NR: 153,
  NP: 154,
  NL: 155,
  AN: 156,
  NC: 157,
  NZ: 158,
  NI: 159,
  NE: 160,
  NG: 161,
  NU: 162,
  NF: 163,
  KP: 164,
  XI: 165,
  MP: 166,
  NO: 167,
  OM: 168,
  PK: 169,
  PW: 170,
  PS: 171,
  PA: 172,
  PG: 173,
  PY: 174,
  PE: 175,
  PH: 176,
  PN: 177,
  PL: 178,
  PT: 179,
  PR: 180,
  QA: 181,
  RE: 182,
  RO: 183,
  RU: 184,
  RW: 185,
  WS: 186,
  SM: 187,
  ST: 188,
  SA: 189,
  SN: 190,
  RS: 191,
  CS: 192,
  SC: 193,
  SL: 194,
  SG: 195,
  SK: 196,
  SI: 197,
  SB: 198,
  SO: 199,
  ZA: 200,
  GS: 201,
  KR: 202,
  SS: 203,
  SU: 204,
  ES: 205,
  LK: 206,
  SH: 207,
  KN: 208,
  LC: 209,
  PM: 210,
  VC: 211,
  SD: 212,
  SR: 213,
  SJ: 214,
  SZ: 215,
  SE: 216,
  CH: 217,
  SY: 218,
  TW: 219,
  TJ: 220,
  TZ: 221,
  TH: 222,
  TL: 223,
  TG: 224,
  TK: 225,
  TO: 226,
  TT: 227,
  TN: 228,
  TR: 229,
  TM: 230,
  TC: 231,
  TV: 232,
  VI: 233,
  UG: 234,
  UA: 235,
  AE: 236,
  GB: 237,
  UM: 238,
  US: 239,
  UY: 240,
  UZ: 241,
  VU: 242,
  VE: 243,
  VN: 244,
  WF: 245,
  EH: 246,
  YE: 247,
  YU: 248,
  ZR: 249,
  ZM: 250,
  ZW: 251,
};
