export default {
  INVALID_AUTH_TOKEN: 'Invalid or expired token',
  RESOURCES_NOT_FOUND: 'Resources not found',
  USER_NOT_FOUND: 'User not found',
  INTERNAL_SERVER_ERROR: 'Server encountered unexpected error',
  FORBIDDEN: 'You are not authorized to perform this operation',
  FORBIDDEN_RESOURCE_ACCESS: 'You are not authorized to view the resource',
  INVALID_LOGIN_DETAIL: 'Invalid email or password',
  USER_NOT_ACTIVE: 'User is not active',
  CUSTOMER_NOT_ASSIGNED: 'Customer is not assigned to the user',
  STAFF_NOT_ASSIGNED: 'Staff (or store manager) is not assigned to the user',
  STAFF_NOT_STORE_MANAGER: 'Staff is not a store manager',
  REQUEST_BODY_MISSING: 'Request is missing required data',
  STORE_NOT_FOUND_FOR_STAFF: 'Store not found for the given staff',
};
