export default {
  INVALID_AUTH_TOKEN: 'Invalid or expired token',
  RESOURCES_NOT_FOUND: 'Resources not found',
  USER_NOT_FOUND: 'User not found',
  INTERNAL_SERVER_ERROR: 'Server encountered unexpected error',
  FORBIDDEN: 'You are not authorized to perform this operation',
  FORBIDDEN_RESOURCE_ACCESS: 'You are not authorized to view the resource',
  INVALID_LOGIN_DETAIL: 'Invalid email or password',
  USER_NOT_ACTIVE: 'User is not active',
  CUSTOMER_IN_USE_BY_USER: 'Customer is assigned to one of the user',
  CUSTOMER_NOT_ASSIGNED: 'Customer is not assigned to the user',
  STAFF_NOT_ASSIGNED: 'Staff (or store manager) is not assigned to the user',
  STAFF_NOT_STORE_MANAGER: 'Staff is not a store manager',
  REQUEST_BODY_MISSING: 'Request is missing required data',
  STORE_NOT_FOUND_FOR_STAFF: 'Store not found for the given staff',
  RELEASE_DATE_INVALID_FORMAT: 'Release date must be in format YYYY-MM-DD',
  INVALID_RELEASE_DATE: 'Invalid release date provided in query',
  INVALID_RATING: 'Invalid rating provided in query',
  INVALID_PAGE_NUMBER: 'Invalid page number',
  INVALID_ACTOR_BIRTHDATE: 'Invalid birth date provided in query',
  ACTOR_BIRTHDATE_INVALID_FORMAT: 'Birth date must be in format YYYY-MM-DD',
  INVALID_ACTOR_DEATHDATE: 'Invalid death date provided in query',
  ACTOR_DEATHDATE_INVALID_FORMAT: 'Death date must be in format YYYY-MM-DD',
  INVALID_REGISTERED_ON: 'Invalid registered on date',
  REGISTERED_ON_FORMAT: 'Registered on date must be in format YYYY-MM-DD',
  INVALID_ACTOR_POPULARITY: 'Invalid actor popularity provided in query',
  INVALID_CUSTOMER_EMAIL_FORMAT: 'Customer email must be alpha numeric and only example.com domain is allowed',
  INVALID_STAFF_EMAIL_FORMAT: 'Staff email must be alpha numeric and only example.com domain is allowed',
};
