export enum GENRES {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  ANIMATION = 'Animation',
  COMEDY = 'Comedy',
  CRIME = 'Crime',
  DOCUMENTARY = 'Documentary',
  DRAMA = 'Drama',
  FAMILY = 'Family',
  FANTASY = 'Fantasy',
  HISTORY = 'History',
  HORROR = 'Horror',
  MUSIC = 'Music',
  MYSTERY = 'Mystery',
  ROMANCE = 'Romance',
  SCIENCE_FICTION = 'Science Fiction',
  TV_MOVIE = 'TV Movie',
  THRILLER = 'Thriller',
  WAR = 'War',
  WESTERN = 'Western',
}

export const availableGenres = {
  1: GENRES.ACTION,
  2: GENRES.ADVENTURE,
  3: GENRES.ANIMATION,
  4: GENRES.COMEDY,
  5: GENRES.CRIME,
  6: GENRES.DOCUMENTARY,
  7: GENRES.DRAMA,
  8: GENRES.FAMILY,
  9: GENRES.FANTASY,
  10: GENRES.HISTORY,
  11: GENRES.HORROR,
  12: GENRES.MUSIC,
  13: GENRES.MYSTERY,
  14: GENRES.ROMANCE,
  15: GENRES.SCIENCE_FICTION,
  16: GENRES.TV_MOVIE,
  17: GENRES.THRILLER,
  18: GENRES.WAR,
  19: GENRES.WESTERN,
};
