export const availableGenres: { [key: string]: number } = {
  ACTION: 1,
  ADVENTURE: 2,
  ANIMATION: 3,
  COMEDY: 4,
  CRIME: 5,
  DOCUMENTARY: 6,
  DRAMA: 7,
  FAMILY: 8,
  FANTASY: 9,
  HISTORY: 10,
  HORROR: 11,
  MUSIC: 12,
  MYSTERY: 13,
  ROMANCE: 14,
  SCIENCE_FICTION: 15,
  'SCIENCE FICTION': 15,
  SCI_FI: 15,
  TV_MOVIE: 16,
  THRILLER: 17,
  WAR: 18,
  WESTERN: 19,
};
