export enum LANGUAGES {
  AB = 'Abkhazian',
  AA = 'Afar',
  AF = 'Afrikaans',
  AK = 'Akan',
  SQ = 'Albanian',
  AM = 'Amharic',
  AR = 'Arabic',
  AN = 'Aragonese',
  HY = 'Armenian',
  AS = 'Assamese',
  AV = 'Avaric',
  AE = 'Avestan',
  AY = 'Aymara',
  AZ = 'Azerbaijani',
  BM = 'Bambara',
  BA = 'Bashkir',
  EU = 'Basque',
  BE = 'Belarusian',
  BN = 'Bengali',
  BI = 'Bislama',
  BS = 'Bosnian',
  BR = 'Breton',
  BG = 'Bulgarian',
  MY = 'Burmese',
  CN = 'Cantonese',
  CA = 'Catalan',
  CH = 'Chamorro',
  CE = 'Chechen',
  NY = 'Chichewa; Nyanja',
  CV = 'Chuvash',
  KW = 'Cornish',
  CO = 'Corsican',
  CR = 'Cree',
  HR = 'Croatian',
  CS = 'Czech',
  DA = 'Danish',
  DV = 'Divehi',
  NL = 'Dutch',
  DZ = 'Dzongkha',
  EN = 'English',
  EO = 'Esperanto',
  ET = 'Estonian',
  EE = 'Ewe',
  FO = 'Faroese',
  FJ = 'Fijian',
  FI = 'Finnish',
  FR = 'French',
  FY = 'Frisian',
  FF = 'Fulah',
  GD = 'Gaelic',
  GL = 'Galician',
  LG = 'Ganda',
  KA = 'Georgian',
  DE = 'German',
  EL = 'Greek',
  GN = 'Guarani',
  GU = 'Gujarati',
  HT = 'Haitian; Haitian Creole',
  HA = 'Hausa',
  HE = 'Hebrew',
  HZ = 'Herero',
  HI = 'Hindi',
  HO = 'Hiri Motu',
  HU = 'Hungarian',
  IS = 'Icelandic',
  IO = 'Ido',
  IG = 'Igbo',
  ID = 'Indonesian',
  IA = 'Interlingua',
  IE = 'Interlingue',
  IU = 'Inuktitut',
  IK = 'Inupiaq',
  GA = 'Irish',
  IT = 'Italian',
  JA = 'Japanese',
  JV = 'Javanese',
  KL = 'Kalaallisut',
  KN = 'Kannada',
  KR = 'Kanuri',
  KS = 'Kashmiri',
  KK = 'Kazakh',
  KM = 'Khmer',
  KI = 'Kikuyu',
  RW = 'Kinyarwanda',
  KY = 'Kirghiz',
  KV = 'Komi',
  KG = 'Kongo',
  KO = 'Korean',
  KJ = 'Kuanyama',
  KU = 'Kurdish',
  LO = 'Lao',
  LA = 'Latin',
  LV = 'Latvian',
  LB = 'Letzeburgesch',
  LI = 'Limburgish',
  LN = 'Lingala',
  LT = 'Lithuanian',
  LU = 'Luba-Katanga',
  MK = 'Macedonian',
  MG = 'Malagasy',
  MS = 'Malay',
  ML = 'Malayalam',
  MT = 'Maltese',
  ZH = 'Mandarin',
  GV = 'Manx',
  MI = 'Maori',
  MR = 'Marathi',
  MH = 'Marshall',
  MO = 'Moldavian',
  MN = 'Mongolian',
  NA = 'Nauru',
  NV = 'Navajo',
  NR = 'Ndebele',
  ND = 'Ndebele',
  NG = 'Ndonga',
  NE = 'Nepali',
  XX = 'No Language',
  SE = 'Northern Sami',
  NO = 'Norwegian',
  NB = 'Norwegian Bokmål',
  NN = 'Norwegian Nynorsk',
  OC = 'Occitan',
  OJ = 'Ojibwa',
  OR = 'Oriya',
  OM = 'Oromo',
  OS = 'Ossetian; Ossetic',
  PI = 'Pali',
  FA = 'Persian',
  PL = 'Polish',
  PT = 'Portuguese',
  PA = 'Punjabi',
  PS = 'Pushto',
  QU = 'Quechua',
  RM = 'Raeto-Romance',
  RO = 'Romanian',
  RN = 'Rundi',
  RU = 'Russian',
  SM = 'Samoan',
  SG = 'Sango',
  SA = 'Sanskrit',
  SC = 'Sardinian',
  SR = 'Serbian',
  SH = 'Serbo-Croatian',
  SN = 'Shona',
  SD = 'Sindhi',
  SI = 'Sinhalese',
  CU = 'Slavic',
  SK = 'Slovak',
  SL = 'Slovenian',
  SO = 'Somali',
  ST = 'Sotho',
  ES = 'Spanish',
  SU = 'Sundanese',
  SW = 'Swahili',
  SS = 'Swati',
  SV = 'Swedish',
  TL = 'Tagalog',
  TY = 'Tahitian',
  TG = 'Tajik',
  TA = 'Tamil',
  TT = 'Tatar',
  TE = 'Telugu',
  TH = 'Thai',
  BO = 'Tibetan',
  TI = 'Tigrinya',
  TO = 'Tonga',
  TS = 'Tsonga',
  TN = 'Tswana',
  TR = 'Turkish',
  TK = 'Turkmen',
  TW = 'Twi',
  UG = 'Uighur',
  UK = 'Ukrainian',
  UR = 'Urdu',
  UZ = 'Uzbek',
  VE = 'Venda',
  VI = 'Vietnamese',
  VO = 'Volapük',
  WA = 'Walloon',
  CY = 'Welsh',
  WO = 'Wolof',
  XH = 'Xhosa',
  II = 'Yi',
  YI = 'Yiddish',
  YO = 'Yoruba',
  ZA = 'Zhuang',
  ZU = 'Zulu',
}

export const availableMovieLanguages: { [key: string]: number } = {
  AB: 1,
  AA: 2,
  AF: 3,
  AK: 4,
  SQ: 5,
  AM: 6,
  AR: 7,
  AN: 8,
  HY: 9,
  AS: 10,
  AV: 11,
  AE: 12,
  AY: 13,
  AZ: 14,
  BM: 15,
  BA: 16,
  EU: 17,
  BE: 18,
  BN: 19,
  BI: 20,
  BS: 21,
  BR: 22,
  BG: 23,
  MY: 24,
  CN: 25,
  CA: 26,
  CH: 27,
  CE: 28,
  NY: 29,
  CV: 30,
  KW: 31,
  CO: 32,
  CR: 33,
  HR: 34,
  CS: 35,
  DA: 36,
  DV: 37,
  NL: 38,
  DZ: 39,
  EN: 40,
  EO: 41,
  ET: 42,
  EE: 43,
  FO: 44,
  FJ: 45,
  FI: 46,
  FR: 47,
  FY: 48,
  FF: 49,
  GD: 50,
  GL: 51,
  LG: 52,
  KA: 53,
  DE: 54,
  EL: 55,
  GN: 56,
  GU: 57,
  HT: 58,
  HA: 59,
  HE: 60,
  HZ: 61,
  HI: 62,
  HO: 63,
  HU: 64,
  IS: 65,
  IO: 66,
  IG: 67,
  ID: 68,
  IA: 69,
  IE: 70,
  IU: 71,
  IK: 72,
  GA: 73,
  IT: 74,
  JA: 75,
  JV: 76,
  KL: 77,
  KN: 78,
  KR: 79,
  KS: 80,
  KK: 81,
  KM: 82,
  KI: 83,
  RW: 84,
  KY: 85,
  KV: 86,
  KG: 87,
  KO: 88,
  KJ: 89,
  KU: 90,
  LO: 91,
  LA: 92,
  LV: 93,
  LB: 94,
  LI: 95,
  LN: 96,
  LT: 97,
  LU: 98,
  MK: 99,
  MG: 100,
  MS: 101,
  ML: 102,
  MT: 103,
  ZH: 104,
  GV: 105,
  MI: 106,
  MR: 107,
  MH: 108,
  MO: 109,
  MN: 110,
  NA: 111,
  NV: 112,
  NR: 113,
  ND: 114,
  NG: 115,
  NE: 116,
  XX: 117,
  SE: 118,
  NO: 119,
  NB: 120,
  NN: 121,
  OC: 122,
  OJ: 123,
  OR: 124,
  OM: 125,
  OS: 126,
  PI: 127,
  FA: 128,
  PL: 129,
  PT: 130,
  PA: 131,
  PS: 132,
  QU: 133,
  RM: 134,
  RO: 135,
  RN: 136,
  RU: 137,
  SM: 138,
  SG: 139,
  SA: 140,
  SC: 141,
  SR: 142,
  SH: 143,
  SN: 144,
  SD: 145,
  SI: 146,
  CU: 147,
  SK: 148,
  SL: 149,
  SO: 150,
  ST: 151,
  ES: 152,
  SU: 153,
  SW: 154,
  SS: 155,
  SV: 156,
  TL: 157,
  TY: 158,
  TG: 159,
  TA: 160,
  TT: 161,
  TE: 162,
  TH: 163,
  BO: 164,
  TI: 165,
  TO: 166,
  TS: 167,
  TN: 168,
  TR: 169,
  TK: 170,
  TW: 171,
  UG: 172,
  UK: 173,
  UR: 174,
  UZ: 175,
  VE: 176,
  VI: 177,
  VO: 178,
  WA: 179,
  CY: 180,
  WO: 181,
  XH: 182,
  II: 183,
  YI: 184,
  YO: 185,
  ZA: 186,
  ZU: 187,
};
